backend:
  name: github
  repo: Jesseraaij/reisblogjesse
  branch: main
  # We halen base_url en auth_endpoint weg, want die hebben we niet meer nodig!

media_folder: "fotos"
public_folder: "/fotos"

collections:
  - name: "reizen"
    label: "Reisverhalen"
    folder: "verhalen"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Omslagfoto", name: "thumbnail", widget: "image", required: false}
      - {label: "Jouw Verhaal", name: "body", widget: "markdown"}